name: OSV-Scanner

on:
  pull_request:
    branches: [ "master" ]
  merge_group:
    branches: [ "master" ]
  schedule:
    - cron: '31 8 * * 3'
  push:
    branches: [ "master" ]

permissions:
  security-events: write
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@a345acffa64b0eaede81a3d9aae6141214d9c8fc" # v2.6.0
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78" # v1.7.1
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
  osv-scan:
    name: OSV-Scanner Scan
    runs-on: ubuntu-24.04 # Pinning to 24.04 clears the ubuntu-latest warning
    steps:
      # 1. Repository Checkout (Pinned to v4.2.2)
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 

      # 2. Run the OSV-Scanner Action directly (Pinned to v1.7.1)
      - name: Run OSV-Scanner
        uses: google/osv-scanner-action/osv-scanner-action@1f1242919d8a60496dd1874b24b62b2370ed4c78
        with:
          scan-args: |-
            -r
            --skip-git
            ./

      # 3. Upload Results to GitHub Security Tab (Pinned to v3.28.10)
      - name: Upload SARIF report
        if: always() # Ensures results upload even if vulnerabilities are found
        uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d 
        with:
          sarif_file: results.sarif
